const elements = [
    { numero: 1, simbolo:"H", nombre: "Hidrogeno", categoria: "nometal", row: 1, col: 1 },
    { numero: 2, simbolo:"He", nombre: "Helio", categoria: "gasesnobles", row: 1, col: 18 },
    { numero: 3, simbolo: 'Li', nombre: 'Litio', categoria: 'alcalino', row: 2, col: 1 },
    { numero: 4, simbolo: 'Be', nombre: 'Berilio', categoria: 'alcalinoterreos', row: 2, col: 2 },
    { numero: 5, simbolo:  'B', nombre: 'Boro', categoria: 'metaloide', row:2, col: 13 },
    { numero: 6, simbolo:  'C', nombre: 'Carbono', categoria: 'nometal', row: 2, col: 14},
    { numero: 7, simbolo:  'N', nombre: 'Nitrógeno', categoria: 'nometal', row: 2, col: 15 },
    { numero: 8, simbolo:  'O', nombre: 'Oxígeno', categoria: 'nometal', row: 2, col: 16 },
    { numero: 9, simbolo:  'F',  nombre: 'Flúor', categoria: 'halogenos', row: 2, col: 17 },
    { numero: 10, simbolo: 'Ne', nombre: 'Neón', categoria: 'gasesnobles', row: 2, col: 18 },
    { numero: 11, simbolo: 'Na', nombre: 'Sodio', categoria: 'alcalino', row: 3, col: 1 },
    { numero: 12, simbolo: 'Mg', nombre: 'Magnesio', categoria: 'alcalinoterreos', row: 3, col: 2 },
    { numero: 13, simbolo: 'Al', nombre: 'Aluminio', categoria: 'despuestransicion', row: 3, col: 13 },
    { numero: 14, simbolo: 'Si', nombre: 'Silicio', categoria: 'metaloide', row: 3, col: 14 },
    { numero: 15, simbolo: 'P', nombre: 'Fósforo', categoria: 'nometal', row: 3, col: 15 },
    { numero: 16, simbolo: 'S', nombre: 'Azufre', categoria: 'nometal', row: 3, col: 16 },
    { numero: 17, simbolo: 'Cl', nombre: 'Cloro', categoria: 'halogenos', row: 3, col: 17 },
    { numero: 18, simbolo: 'Ar', nombre: 'Argón', categoria: 'gasesnobles', row: 3, col: 18 },
    { numero: 19, simbolo: 'K', nombre: 'Potasio', categoria: 'alcalino', row: 4, col: 1 },
    { numero: 20, simbolo: 'Ca', nombre: 'Calcio', categoria: 'alcalinoterreos', row: 4, col: 2 },
    { numero: 21, simbolo: 'Sc', nombre: 'Escandio', categoria: 'transicion', row: 4, col: 3 },
    { numero: 22, simbolo: 'Ti', nombre: 'Titanio',categoria : 'transicion', row: 4, col: 4 },
    { numero: 23, simbolo: 'V', nombre: 'Vanadio', categoria: 'transicion', row: 4, col: 5 },
    { numero: 24, simbolo: 'Cr', nombre: 'Cromo', categoria: 'transicion', row: 4, col: 6 },
    {nummro : 25, simbolo: 'Mn', nombre: 'Manganeso', categoria: 'transicion', row: 4, col: 7 },
    { numero: 26, simbolo: 'Fe', nombre: 'Hierro', categoria: 'transicion', row: 4, col: 8 },
    { numero: 27, simbolo: 'Co', nombre: 'Cobalto', categoria: 'transicion', row: 4, col: 9 },
    { numero: 28, simbolo: 'Ni', nombre: 'Níquel', categoria: 'transicion', row: 4, col: 10 },
    { numero: 29, simbolo: 'Cu', nombre: 'Cobre', categoria: 'transicion', row: 4, col: 11 },
    { numero: 30, simbolo: 'Zn', nombre: 'Zinc', categoria: 'transicion', row: 4, col: 12 },
    { numero: 31, simbolo: 'Ga', nombre: 'Galio', categoria: 'despuestransicion', row: 4, col: 13 },
    { numero: 32, simbolo: 'Ge', nombre: 'Germanio', categoria: 'metaloide', row: 4, col: 14 },
    { numero : 33, simbolo: 'As', nombre: 'Arsénico', categoria: 'metaloide', row: 4, col: 15 },
    { numero: 34, simbolo: 'Se', nombre: 'Selenio', categoria: 'nometal', row: 4, col: 16 },
    { numero: 35, simbolo: 'Br', nombre: 'Bromo', categoria: 'halogenos', row: 4, col: 17 },
    { numero: 36, simbolo: 'Kr', nombre: 'Kriptón', categoria: 'gasesnobles', row: 4, col: 18 },
    { numero: 37, simbolo: 'Rb', nombre: 'Rubidio', categoria: 'alcalino', row: 5, col: 1 },
    { numero: 38, simbolo: 'Sr', nombre: 'Estroncio', categoria: 'alcalinoterreos', row: 5, col: 2 },
    { numero: 39, simbolo: 'Y', nombre: 'Itrio', categoria: 'transicion', row: 5, col: 3 },
    { numero: 40, simbolo: 'Zr', nombre: 'Circonio', categoria: 'transicion', row: 5, col: 4 },
    { numero: 41, simbolo: 'Nb', nombre: 'Niobio', categoria: 'transicion', row: 5, col: 5 },
    { numero: 42, simbolo: 'Mo', nombre: 'Molibdeno', categoria: 'transicion', row: 5, col: 6 },
    { numero: 43, simbolo: 'Tc', nombre: 'Tecnecio', categoria: 'transicion', row: 5, col: 7 },
    { numero : 44, simbolo: 'Ru', nombre: 'Rutenio',categoria: 'transicion', row: 5, col: 8 },
    { numero : 45, simbolo: 'Rh', nombre: 'Rodio', categoria: 'transicion', row: 5, col: 9 },
    { numero : 46, simbolo: 'Pd', nombre: 'Paladio', categoria: 'transicion', row: 5, col: 10 },
    { numero : 47, simbolo: 'Ag', nombre: 'Plata', categoria: 'transicion', row: 5, col: 11 },
    { numero : 48, simbolo: 'Cd', nombre: 'Cadmio', categoria: 'transicion', row: 5, col: 12},
    { numero : 49, simbolo: 'In', nombre: 'Indio', categoria: 'despuestransicion', row: 5, col: 13 },
    { numero : 50, simbolo: 'Sn', nombre: 'Estaño', categoria: 'despuestransicion', row: 5, col: 14 },
    { numero : 51, simbolo: 'Sb', nombre: 'Antimonio', categoria: 'metaloide', row: 5, col: 15},
    { numero : 52, simbolo: 'Te', nombre: 'Telurio', categoria: 'metaloide', row: 5, col: 16 },
    { numero : 53, simbolo: 'I', nombre: 'Yodo', categoria: 'halogenos', row: 5, col: 17 },
    { numero : 54, simbolo: 'Xe', nombre: 'Xenón', categoria: 'gasesnobles', row: 5, col: 18 },
    { numero : 55, simbolo: 'Cs', nombre: 'Cesio', categoria: 'alcalino', row: 6, col: 1 },
    { numero : 56, simbolo: 'Ba', nombre: 'Bario', categoria: 'alkalinoterreos', row: 6, col: 2 },
    { numero : 57, simbolo: 'La', nombre: 'Lantano', categoria: 'lantanidos', row: 9, col: 4 },
    { numero : 58, simbolo: 'Ce', nombre: 'Cerio', categoria: 'lantanidos', row: 9, col: 5 },
    { numero : 59, simbolo: 'Pr', nombre: 'Praseodimio', categoria: 'lantanidos', row: 9, col: 6 },
    { numero : 60, simbolo: 'Nd', nombre: 'Neodimio', categoria: 'lantanidos', row: 9, col: 7},
    { numero : 61, simbolo: 'Pm', nombre: 'Prometio', categoria: 'lantanidos', row: 9, col: 8 },
    { numero : 62, simbolo: 'Sm', nombre: 'Samario', categoria: 'lantanidos', row: 9, col: 9 },
    { numero : 63, simbolo: 'Eu', nombre: 'Europio', categoria: 'lantanidos', row: 9, col: 10},
    { numero : 64, simbolo: 'Gd', nombre: 'Gadolinio', categoria: 'lantanidos', row: 9, col: 11 },
    { numero : 65, simbolo: 'Tb', nombre: 'Terbio', categoria: 'lantanidos', row: 9, col: 12 },
    { numero : 66, simbolo: 'Dy', nombre: 'Disprosio', categoria: 'lantanidos', row: 9, col: 13 },
    { numero : 67, simbolo: 'Ho', nombre: 'Holmio', categoria: 'lantanidos', row: 9, col: 14 },
    { numero : 68, simbolo: 'Er', nombre: 'Erbio', categoria: 'lantanidos', row: 9, col: 15 },
    { numero : 69, simbolo: 'Tm', nombre: 'Tulio', categoria: 'lantanidos', row: 9, col: 16 },
    { numero : 70, simbolo: 'Yb', nombre: 'Iterbio', categoria: 'lantanidos', row: 9, col: 17 },
    { numero : 71, simbolo: 'Lu', nombre: 'Lutecio', categoria: 'lantanidos', row: 6, col: 3 },
    { numero : 72, simbolo: 'Hf', nombre: 'Hafnio', categoria: 'transicion', row: 6, col: 4 },
    { numero : 73, simbolo: 'Ta', nombre: 'Tantalio', categoria: 'transicion', row: 6, col: 5 },
    { numero : 74, simbolo: 'W', nombre: 'Wolframio',categoria: 'transicion', row: 6, col: 6 },
    { numero : 75, simbolo: 'Re', nombre: 'Renio', categoria: 'transicion', row: 6, col: 7 },
    { numero : 76, simbolo: 'Os', nombre: 'Osmio', categoria: 'transicion', row: 6, col: 8 },
    { numero : 77, simbolo: 'Ir', nombre: 'Iridio', categoria: 'transicion', row: 6, col: 9 },
    { numero : 78, simbolo: 'Pt', nombre: 'Platino', categoria: 'transicion', row: 6, col: 10 },
    { numero : 79, simbolo: 'Au', nombre: 'Oro', categoria: 'transicion', row: 6, col: 11 },
    { numero : 80, simbolo: 'Hg', nombre: 'Mercurio', categoria: 'transicion', row: 6, col: 12 },
    { numero : 81, simbolo: 'Tl', nombre: 'Talio', categoria: 'despuestransicion', row: 6, col: 13 },
    { numero : 82, simbolo: 'Pb', nombre: 'Plomo', categoria:'despuestransicion', row: 6, col: 14 },
    { numero : 83, simbolo: 'Bi', nombre: 'Bismuto', categoria: 'despuestransicion', row: 6, col: 15 },
    { numero : 84, simbolo: 'Po', nombre: 'Polonio', categoria: 'despuestransicion', row: 6, col: 16 },
    { numero : 85, simbolo: 'At', nombre: 'Ástato', categoria: 'halogenos', row: 6, col: 17 },
    { numero : 86, simbolo: 'Rn', nombre: 'Radón', categoria: 'gasesnobles', row: 6, col: 18 },
    { numero : 87, simbolo: 'Fr', nombre: 'Francio', categoria: 'alcalinos', row: 7, col: 1 },
    { numero : 88, simbolo: 'Ra', nombre: 'Radio', categoria: 'alcalinoterreos', row: 7, col: 2 },
    { numero : 89, simbolo: 'Ac', nombre: 'Actinio', categoria: 'actinidos', row: 10, col: 4 },
    { numero : 90, simbolo: 'Th', nombre: 'Torio', categoria: 'actinidos', row: 10, col: 5 },
    { numero : 91, simbolo: 'Pa', nombre: 'Protactinio', categoria: 'actinidos', row: 10, col: 6 },
    { numero : 92, simbolo: 'U', nombre: 'Uranio', categoria: 'actinidos', row: 10, col: 7},
    { numero : 93, simbolo: 'Np', nombre: 'Neptunio', categoria: 'actinidos', row: 10, col: 8 },
    { numero : 94, simbolo: 'Pu', nombre: 'Plutonio',categoria : 'actinidos', row: 10, col: 9 },
    { numero : 95, simbolo: 'Am', nombre: 'Americio',categoria : 'actinidos', row: 10, col: 10 },
    { numero : 96, simbolo: 'Cm', nombre: 'Curio',categoria : 'actinidos', row: 10, col: 11 },
    { numero : 97, simbolo: 'Bk', nombre: 'Berkelio', categoria: 'actinidos', row: 10, col: 12 },
    { numero : 98, simbolo: 'Cf', nombre: 'Californio',categoria : 'actinidos', row: 10, col: 13 },
    { numero : 99, simbolo: 'Es', nombre: 'Einstenio', categoria: 'actinidos', row: 10, col: 14 },
    { numero : 100, simbolo: 'Fm', nombre: 'Fermio', categoria: 'actinidos', row: 10, col: 15 },
    { numero : 101, simbolo: 'Md', nombre: 'Mendelevio',categoria : 'actinidos', row: 10, col: 16 },
    { numero : 102, simbolo: 'No', nombre: 'Nobelio', categoria: 'actinidos', row: 10, col: 17 },
    { numero : 103, simbolo: 'Lr', nombre: 'Lawrencio', categoria: 'actinidos', row: 7, col: 3 },
    { numero : 104, simbolo: 'Rf', nombre: 'Rutherfordio', categoria: 'transicion', row: 7, col: 4 },
    { numero : 105, simbolo: 'Db', nombre: 'Dubnio', categoria: 'transicion', row: 7, col: 5 },
    { numero : 106, simbolo: 'Sg', nombre: 'Seaborgio', categoria: 'transicion', row: 7, col: 6 },
    { numero : 107, simbolo: 'Bh', nombre: 'Bohrio', categoria: 'transicion', row: 7, col: 7 },
    { numero : 108, simbolo: 'Hs', nombre: 'Hassio', categoria: 'transicion', row: 7, col: 8 },
    { numero : 109, simbolo: 'Mt', nombre: 'Meitnerio', categoria: 'transicion', row: 7, col: 9 },
    { numero : 110, simbolo: 'Ds', nombre: 'Darmstadtio', categoria: 'transicion', row: 7, col: 10 },
    { numero : 111, simbolo: 'Rg', nombre: 'Roentgenio', categoria: 'transicion', row: 7, col: 11 },
    { numero : 112, simbolo: 'Cn', nombre: 'Copernicio', categoria: 'transicion', row: 7, col: 12 },
    { numero : 113, simbolo: 'Nh', nombre: 'Nihonio', categoria: 'despuestransicion', row: 7, col: 13 },
    { numero : 114, simbolo: 'Fl', nombre: 'Flerovio', categoria: 'despuestransicion', row: 7, col: 14 },
    { numero : 115, simbolo: 'Mc', nombre: 'Moscovio', categoria: 'despuestransicion', row: 7, col: 15 },
    { numero : 116, simbolo: 'Lv', nombre: 'Livermorio', categoria: 'despuestransicion', row: 7, col: 16 },
    { numero : 117, simbolo: 'Ts', nombre: 'Teneso', categoria: 'halogeno', row: 7, col: 17 },
    { numero : 118, simbolo: 'Og', nombre: 'Oganesón',categoria: 'gasesnobles', row: 7, col: 18 },
]
    
    
    